# smd TOML config file
# If both VSOP87 and SPICE are enabled, smd will panic
[general]
output_path = "./outputs/" # Defines the output directory. Use "./" to output to current working directory.
test_export = false # Set to true to export the test cases.

[Meeus]
enabled = false

[SPICE]
directory = "../../../../cmd/refframes"
horizonDir = "../../../../data/horizon"
horizonCSV = true
truncation = "1m"
