sudo: required
language: go
go:
  - 1.7
addons:
  apt:
    sources:
      - deadsnakes # source required so it finds the package definition below
    packages:
      - python3.4
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - sudo pip install virtualenv
  - virtualenv -p `which python3.4` .venv
  - source .venv/bin/activate
  - python -V
  - pip -V
  - pip install -r cmd/refframes/reqs.txt
  - wget -O cmd/refframes/spicekernels/de430.bsp https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430.bsp
script:
  - python cmd/refframes/tests.py
  - go test -v -timeout=30m -covermode=count -coverprofile=coverage.out
  #- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
  - $HOME/gopath/bin/goveralls -package github.com/ChristopherRabotin/smd -service=travis-ci
