# smd TOML config file
# If both VSOP87 and SPICE are enabled, smd will panic
[general]
output_path = "./" # Defines the output directory. Use "./" to output to current working directory.

[VSOP87]
enabled = false
directory = "./data/vsop87"

[SPICE]
enabled = true
directory = "./cmd/refframes"
