[General]
fileprefix = "fp3ee"
verbose = true
c3plot = false

#[Arrival]
#planet = "Earth"
#from = "2028-02-15 00:00:00" # Supports both Julian dates (must be floats) and "YYYY-MM-DD HH:MM:SS".
#until = "2028-03-16 00:00:00"
#resolution = 1 # Number of points per day. For example, set to 24 for one point per hour.
#
#[Departure]
#planet = "Earth"
#from = "2025-02-15 00:00:00" # Supports both Julian dates (must be floats) and "YYYY-MM-DD HH:MM:SS".
#until = "2025-03-16 00:00:00"
#resolution = 1 # Number of points per day. For example, set to 24 for one point per hour.

[Arrival]
planet = "Earth"
from = "2026-12-01 00:00:00" # Supports both Julian dates (must be floats) and "YYYY-MM-DD HH:MM:SS".
until = "2027-04-01 00:00:00"
resolution = 1 # Number of points per day. For example, set to 24 for one point per hour.

[Departure]
planet = "Earth"
from = "2025-02-15 00:00:00" # Supports both Julian dates (must be floats) and "YYYY-MM-DD HH:MM:SS".
until = "2025-03-16 00:00:00"
resolution = 1 # Number of points per day. For example, set to 24 for one point per hour.
