[General]
fileprefix = "fp0ev"
verbose = true
c3plot = true

[Departure]
planet = "Earth"
from = 2461291.5
until = 2461311.5
resolution = 1

[Arrival]
planet = "Venus"
from =  2461449.5
until = 2461469.5
resolution = 1
