[General]
fileprefix = "fp3ee"
verbose = true
c3plot = false

[Arrival]
planet = "Earth"
from = "2026-03-01 00:00:00" # Supports both Julian dates (must be floats) and "YYYY-MM-DD HH:MM:SS".
until = "2026-05-01 00:00:00"
resolution = 1 # Number of points per day. For example, set to 24 for one point per hour.

[Departure]
planet = "Earth"
from = "2024-03-01 00:00:00" # Supports both Julian dates (must be floats) and "YYYY-MM-DD HH:MM:SS".
until = "2026-05-01 00:00:00"
resolution = 1 # Number of points per day. For example, set to 24 for one point per hour.
