[General]
fileprefix = "fp2me"
verbose = true
c3plot = false

[Arrival]
planet = "Earth"
from = "2024-04-01 00:00:00" # Supports both Julian dates (must be floats) and "YYYY-MM-DD HH:MM:SS".
until = "2024-05-30 00:00:00"
resolution = 1 # Number of points per day. For example, set to 24 for one point per hour.

[Departure]
planet = "Mars"
from = "2022-01-01 00:00:00" # Supports both Julian dates (must be floats) and "YYYY-MM-DD HH:MM:SS".
until = "2023-01-01 00:00:00"
resolution = 1 # Number of points per day. For example, set to 24 for one point per hour.
