[General]
fileprefix = "gvga"
verbose = true
c3plot = false

[Departure]
planet = "Earth"
from = "1989-08-15 00:00:00" # Supports both Julian dates (must be floats) and "YYYY-MM-DD HH:MM:SS".
until = "1989-12-15 00:00:00"
resolution = 1 # Number of points per day. For example, set to 24 for one point per hour.

[Arrival]
planet = "Venus"
from = "1989-12-01 00:00:00"
until = "1990-05-01 00:00:00"
resolution = 1 # Number of points per day. For example, set to 24 for one point per hour.
