[general]
fileprefix = "veej"
verbose = true
step = "24h"
flybyplanets = "Venus Earth Earth"

[launch]
planet = "Earth"
from = "2020-01-09 00:00:00"
until = "2021-01-01 00:00:00"
maxC3 = 18 # Max c3 allowed

[arrival]
planet = "Jupiter"
until = "2030-01-01 00:00:00"
maxVinf = 6

[flyby.Venus]
position = 1
deltaV = 1.0
periapsis = 1.1

[flyby.Earth]
position = 2
deltaV = 1.0
periapsis = 1.1

[flyby.Earth.1]
position = 3
deltaV = 1.0
periapsis = 1.1
