[general]
fileprefix = "prj-neptune"
outputdir = "outputs"
verbose = true
step = "24h"
flybyplanets = "Venus Earth Jupiter"

[launch]
planet = "Earth"
from = 2461250.5
until = 2461350.5
resolution = 1
maxC3 = 40

[arrival]
planet = "Neptune"
from = 2468545.5
until = 2468625.5
maxVinf = 18

[flyby.Venus]
position = 1
from = 2461408.5
until = 2461510.5
deltaV = 1.0
periapsis = 1.01

[flyby.Earth]
# First passage dates, the second is determined by the resonance type.
position = 2
deltaV = 1.0
from = 2461710.5
until = 2461810.5
periapsis = 1.05
resonant = true
resonance = 2

[flyby.Jupiter]
position = 3
deltaV = 1.0
from = 2463340.5
until = 2463410.5
periapsis = 4.0
