[general]
fileprefix = "prj"
verbose = true
step = "24h"
flybyplanets = "Venus Mars Earth Earth Saturn"

[launch]
planet = "Earth"
from = "2023-01-01 00:00:00"
until = "2024-01-01 00:00:00"
maxC3 = 35

[arrival]
planet = "Uranus"
until = "2044-01-01 00:00:00"
maxVinf = 10

[flyby.Venus]
position = 1
deltaV = 1.0
periapsis = 1.1

[flyby.Mars]
position = 2
deltaV = 1.0
periapsis = 1.1

[flyby.Earth]
position = 3
deltaV = 1.0
periapsis = 1.1

[flyby.Earth.1]
position = 4
deltaV = 1.0
periapsis = 1.1

[flyby.Saturn]
position = 5
deltaV = 1.0
periapsis = 4.0
