[general]
fileprefix = "prj"
outputdir = "outputs"
verbose = true
step = "24h"
flybyplanets = "Venus Earth Earth Jupiter"

[launch]
planet = "Earth"
from = 2461300.5
until = 2461302.5
resolution = 1
maxC3 = 40

[arrival]
planet = "Neptune"
from = 2468592.5
until = 2468595.5
maxVinf = 18

[flyby.Venus]
from = 2461458.0
until = 2461460.5
position = 1
deltaV = 2.0
periapsis = 1.01

[flyby.Earth]
# First passage dates, the second is determined by the resonance type.
position = 2
deltaV = 2.0
from = 2461766.5
until = 2461768.5
periapsis = 1.05
resonant = true
resonance = 3

[flyby.Jupiter]
position = 4
deltaV = 2.0
from = 2463384.5
until = 2463386.5
periapsis = 4.0
