[general]
fileprefix = "prj-neptune"
outputdir = "outputs"
verbose = true
step = "24h"
flybyplanets = "Venus Earth Jupiter"

[launch]
planet = "Earth"
from = "2026-07-15 00:00:00"
until = "2026-09-15 00:00:00"
resolution = 1
maxC3 = 13

[arrival]
planet = "Neptune"
from = "2048-06-25 00:00:00"
until = "2051-07-01 00:00:00"
maxVinf = 7

[flyby.Venus]
position = 1
from = "2027-02-15 00:00:00"
until = "2027-03-26 00:00:00"
deltaV = 0.91
periapsis = 1.01

[flyby.Earth]
position = 2
deltaV = 1.0
from = "2027-12-04 00:00:00"
until = "2028-01-15 00:00:00"
periapsis = 1.01
resonant = true
resonance = 2

[flyby.Jupiter]
position = 3
deltaV = 0.6
from = "2031-12-01 00:00:00"
until = "2032-10-31 00:00:00"
periapsis = 2.5
