[general]
fileprefix = "galileo"
outputdir = "outputs"
verbose = true
step = "24h"
flybyplanets = "Venus Earth"

[launch]
planet = "Earth"
from = "1989-10-07 00:00:00"
until = "1989-10-09 00:00:00"
maxC3 = 50 # Max c3 allowed

[arrival]
planet = "Jupiter"
from = "1996-03-20 00:00:00"
until = "1996-03-23 00:00:00"
maxVinf = 20

[flyby.Venus]
position = 1
from = "1990-02-09 00:00:00"
until = "1990-02-11 00:00:00"
deltaV = 0.9

[flyby.Earth]
# First passage dates, the second is determined by the resonance type.
position = 2
deltaV = 2.0
from = "1990-12-09 00:00:00"
until = "1990-12-11 00:00:00"
periapsis = 1.05
resonant = true
resonance = 2
