[General]
fileprefix = "nh"
verbose = true
from = "2006-01-09 00:00:00"
until = 2457517.5
step = "24h"
planets = "Jupiter Pluto"
periRFactor = "4.0 10" # Factor of minimum periapsis radii based on the radius of the planet
maxDeltaV = "3.0 3.0" # Maximum delta-V allowed per passage.

[DepartureConstraints]
c3 = 180 # Max c3 allowed
[ArrivalConstraints]
vInf = 14.5 # Max v infinity at destination
