[measurements]
file = "../mission/output/sampling10s.csv"
stations = ["MSLCuriosity", "ExoMars"]

[station.MSLCuriosity]
name = "MSL Curiosity"
altitude = 5.5
elevation = 25
latitude = -4.5895
longitude = 137.4417
range_sigma = 0.5
rate_sigma = 0.5
planet = "Mars"

[station.ExoMars]
name = "ExoMars"
altitude = -0.5
elevation = 10
latitude = -2.7
longitude = 16.7
range_sigma = 0.1
rate_sigma = 0.1
planet = "Mars"

[mission]
autodate = true # The dates below are not used.
start = "2015-02-03 00:00:00"
end = "2015-02-03 00:30:00"
step = "1s"

[filter]
type = "EKF" # Or `CKF` or `UKF`; defines the section to be read.
outPrefix = "output/prj30s" # Prefix used for all filtering.

[noise]
Q = 1e-12
range = 1e-3
rate = 1e-6

[covariance]
position = 10
velocity = 0.01

[CKF]
smooth = false

[EKF]
trigger = 15 # Number of measurements prior to switching to EKF mode.
disableTime = -1 # Seconds between measurements to switch back to CKF. Set as negative to ignore.

[burns.0]
date = "2016-10-19 00:00:00"
R = 0
N = -0.15
C = 0

[burns.1]
date = "2016-10-19 00:00:01"
R = 0
N = -0.15
C = 0

[burns.2]
date = "2016-10-19 00:00:02"
R = 0
N = -0.35
C = 0

[burns.3]
date = "2016-10-19 00:00:03"
R = 0
N = -0.35
C = 0

[burns.4]
date = "2016-10-19 00:00:04"
R = 0
N = -0.35
C = 0

[burns.5]
date = "2016-10-19 00:00:05"
R = 0
N = -0.35
C = 0

[burns.6]
date = "2016-10-19 00:00:06"
R = 0
N = -0.35
C = 0

[burns.7]
date = "2016-10-19 00:00:07"
R = 0
N = -0.35
C = 0

[burns.8]
date = "2016-10-19 00:00:08"
R = 0
N = -0.35
C = 0

[burns.9]
date = "2016-10-19 00:00:09"
R = 0
N = -0.35
C = 0

[burns.10]
date = "2016-10-19 00:00:10"
R = 0
N = -0.35
C = 0

[burns.11]
date = "2016-10-19 00:00:11"
R = 0
N = -0.35
C = 0

[burns.12]
date = "2016-10-19 00:00:12"
R = 0
N = -0.35
C = 0

[burns.13]
date = "2016-10-19 00:00:13"
R = 0
N = -0.35
C = 0

[burns.14]
date = "2016-10-19 00:00:14"
R = 0
N = -0.35
C = 0

[burns.15]
date = "2016-10-19 00:00:15"
R = 0
N = -0.35
C = 0

[burns.16]
date = "2016-10-19 00:00:16"
R = 0
N = -0.35
C = 0

[burns.17]
date = "2016-10-19 00:00:17"
R = 0
N = -0.35
C = 0

[burns.18]
date = "2016-10-19 00:00:18"
R = 0
N = -0.35
C = 0

[burns.19]
date = "2016-10-19 00:00:19"
R = 0
N = -0.35
C = 0

#[burns.20]
#date = "2016-10-19 00:00:20"
#R = 0
#N = -0.05
#C = 0

[orbit]
body = "Mars"
sma = 55855.7
ecc = 0.8690
inc = 74.0
RAAN = 0.0
argPeri = 0.0
tAnomaly = 180

[perturbations]
J2 = true
J3 = false
J4 = false
bodies = ["Earth", "Sun", "Venus", "Jupiter"]
