[measurements]
file = "../mission/output/sampling2s-burn.csv"
stations = ["MSLCuriosity", "ExoMars"]

[station.MSLCuriosity]
name = "MSL Curiosity"
altitude = 5.5
elevation = 25
latitude = -4.6
longitude = 137.4
range_sigma = 5e-3
rate_sigma = 5e-6
planet = "Mars"

[station.ExoMars]
name = "ExoMars"
altitude = -0.5
elevation = 5
latitude = -2.7
longitude = 255.0
range_sigma = 5e-3
rate_sigma = 5e-6
planet = "Mars"

[mission]
autodate = false
proptostart = false
start = "2016-10-18 23:59:58" # or JDE
end = "2016-10-20 00:00:00" # or JDE
#start = "2016-10-16 16:20:06" # or JDE
#end = "2016-10-22 00:00:00" # or JDE
step = "1s"

[spacecraft]
name = "TGO"
fuel = 500
dry = 500

[filter]
type = "EKF" # Or `CKF` or `UKF`; defines the section to be read.
outPrefix = "output/prj2s" # Prefix used for all filtering.
start = "2016-10-18 18:59:59"
end = "2016-10-19 00:15:00"

[noise]
Q = 1e-12
range = 1e-3
rate = 1e-6

[covariance]
position = 10
velocity = 0.01

[CKF]
smooth = false

[EKF]
trigger = 65 # Number of measurements prior to switching to EKF mode.
disableTime = -1 # Seconds between measurements to switch back to CKF. Set as negative to ignore.

[burns.0]
date = "2016-10-19 00:00:00"
R = 0
N = -0.35
C = 0

[burns.1]
date = "2016-10-19 00:00:01"
R = 0
N = -0.35
C = 0

[burns.2]
date = "2016-10-19 00:00:02"
R = 0
N = -0.35
C = 0

[burns.3]
date = "2016-10-19 00:00:03"
R = 0
N = -0.35
C = 0

[burns.4]
date = "2016-10-19 00:00:04"
R = 0
N = -0.35
C = 0

[burns.5]
date = "2016-10-19 00:00:05"
R = 0
N = -0.35
C = 0

[burns.6]
date = "2016-10-19 00:00:06"
R = 0
N = -0.35
C = 0

[burns.7]
date = "2016-10-19 00:00:07"
R = 0
N = -0.35
C = 0

[burns.8]
date = "2016-10-19 00:00:08"
R = 0
N = -0.35
C = 0

[burns.9]
date = "2016-10-19 00:00:09"
R = 0
N = -0.35
C = 0

[burns.10]
date = "2016-10-19 00:00:10"
R = 0
N = -0.35
C = 0

[burns.11]
date = "2016-10-19 00:00:11"
R = 0
N = -0.35
C = 0

[burns.12]
date = "2016-10-19 00:00:12"
R = 0
N = -0.35
C = 0

[burns.13]
date = "2016-10-19 00:00:13"
R = 0
N = -0.35
C = 0

[burns.14]
date = "2016-10-19 00:00:14"
R = 0
N = -0.35
C = 0

[burns.15]
date = "2016-10-19 00:00:15"
R = 0
N = -0.35
C = 0

[burns.16]
date = "2016-10-19 00:00:16"
R = 0
N = -0.35
C = 0

[burns.17]
date = "2016-10-19 00:00:17"
R = 0
N = -0.35
C = 0

[burns.18]
date = "2016-10-19 00:00:18"
R = 0
N = -0.35
C = 0

[burns.19]
date = "2016-10-19 00:00:19"
R = 0
N = -0.35
C = 0

[orbit]
body = "Mars"
#a=55839.0 e=0.8692 i=74.040 Ω=0.007 ω=0.019 ν=230.325
sma = 55839.7
ecc = 0.8692
inc = 74.0040
RAAN = 0.007
argPeri = 0.019
tAnomaly = 230.325
#sma = 55855.7
#ecc = 0.8690
#inc = 74.0
#RAAN = 0.0
#argPeri = 0.0
#tAnomaly = 180

[perturbations]
J2 = true
J3 = false
J4 = false
bodies = ["Earth", "Sun", "Venus", "Jupiter"]
